### ISSUE TITLE
Pull in fedux_org-stdlib

### ISSUE THREAD

**Issue by maxmeyer** [jasonlong/geo_pattern#43]
Is it ok to pull in fedux_org-stdlib for development? It's a library of mine I use to give code snippets a home. :smile:

**Comment by maxmeyer** [comment]
It's more or less build like activesupport. You need to require all things explicitly you want to use.

**Comment by jasonlong** [comment]
I'm not clear what the purpose of this is. I'd like to keep dependencies to a minimum personally.

**Comment by maxmeyer** [comment]
Oh. Wrong repository. Should have gone to geo_pattern-cli. Sorry for that.
