### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by jasonlong** [jasonlong/geo_pattern#48]
@maxmeyer Looks like something isn't quite right with the build setup. I renamed the config file to use `.yml` instead of `.yaml` since Travis was complaining about that and I updated the references to the `script/` directory (which was using `scripts/` previously).

Could you take a peek?
https://travis-ci.org/jasonlong/geo_pattern

**Comment by maxmeyer** [comment]
No problem, I will take a look into that. Thanks for merging.

Excerpts from Jason Long's message of 2015-02-14 06:42:09 -0800:

**Comment by maxmeyer** [comment]
Fixed by #50

**Comment by jasonlong** [comment]
:metal: looks like we're green again!
