### ISSUE TITLE
Feature proposal: abstract triangle backgrounds 

### ISSUE THREAD

**Issue by ilyacherevkov** [jasonlong/geo_pattern#63]
These backgrounds are pretty awesome: http://qrohlf.com/trianglify/
But I can generate them in Node.js only, couldn't find simple way to generate them server-side in ruby. ExecJS and therubyracer cannot compile it.

**Comment by jasonlong** [comment]
Hey @ilyacherevkov – I'm a huge fan of that sort of low-poly style as well, but I likely won't be adding any new patterns to this library. Due to the way it works (using SHA strings with 0-f hex values) only 16 pattern types are available and those are already in place.

**Comment by hendrixfan** [comment]
i made a gem for rendering server-side: [TrianglePatterns](https://github.com/hendrixfan/triangle)
