### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by jasonlong** [jasonlong/geo_pattern#65]
@maxmeyer Any chance you could check out the current failures on Travis? The tests run fine for me locally, so I'm not sure what is different with the Travis config.

**Comment by maxmeyer** [comment]
@jasonlong Sorry for the delay? Did you fix the build yourself?

**Comment by jasonlong** [comment]
@maxmeyer Shoot, I forgot to close this. Yep, got it taken care of in #66. Thanks though!
