### ISSUE TITLE
Ruby 3.0 compatibility?

### ISSUE THREAD

**Issue by nogweii** [jasonlong/geo_pattern#74]
[In the gemspec](https://github.com/jasonlong/geo_pattern/blob/main/geo_pattern.gemspec#L20), it lists being compatible with only Ruby 2.x, but I believe that it should work with ruby 3.0 as well.

**Comment by jasonlong** [comment]
@nogweii You may be right. Unfortunately, I'm no longer maintaining this project since my Ruby chops aren't strong enough to keep up newer versions and CI hasn't passed in quite a while either. I just added a notice about this in the README too.
